Repository octokit/types.ts, pull requests merged in 2023-01, with the labels that each got.

#488 build: npm lint to properly find files on Win OS
  package.json
Labels: Type: Feature

#494 Default branch rename
  .github/pull_request_template.md
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/update.yml
  CONTRIBUTING.md
  package.json
Labels: Type: Maintenance

#491 feat: remove previews
  scripts/update-endpoints/fetch-json.js
  scripts/update-endpoints/generated/endpoints.json
  scripts/update-endpoints/templates/endpoints.ts.template
  scripts/update-endpoints/typescript.js
  src/AuthInterface.ts
  src/EndpointDefaults.ts
  src/EndpointInterface.ts
  src/RequestHeaders.ts
  src/RequestInterface.ts
  src/RequestParameters.ts
  src/generated/Endpoints.ts
Labels: Type: Breaking change, Type: Maintenance

#495 Revert "feat: remove previews (#491)"
  scripts/update-endpoints/fetch-json.js
  scripts/update-endpoints/generated/endpoints.json
  scripts/update-endpoints/templates/endpoints.ts.template
  scripts/update-endpoints/typescript.js
  src/AuthInterface.ts
  src/EndpointDefaults.ts
  src/EndpointInterface.ts
  src/RequestHeaders.ts
  src/RequestInterface.ts
  src/RequestParameters.ts
  src/generated/Endpoints.ts
Labels: Type: Maintenance

#497 build(deps): downgrade `sort-keys` to v4
  package-lock.json
  package.json
Labels: Type: Maintenance
