Repository octokit/types.ts, pull requests merged in 2023-06, with the labels that each got.

#555 fix: remove all potentially undefined parameter types
  scripts/update-endpoints/templates/endpoints.ts.template
  src/generated/Endpoints.ts
Labels: Type: Bug, Priority: High

#556 docs: add comment about optional parameter
  scripts/update-endpoints/templates/endpoints.ts.template
  src/generated/Endpoints.ts
Labels: Type: Documentation

#550 fix(build): use typescript to produce declaration files
  .github/workflows/test.yml
  .github/workflows/update.yml
  package-lock.json
  package.json
  scripts/build.mjs
  test.ts
  tsconfig.json
  tsconfig.test.json
Labels: Type: Maintenance

#547 feat: v10
  scripts/update-endpoints/fetch-json.js
  scripts/update-endpoints/generated/endpoints.json
  scripts/update-endpoints/templates/endpoints.ts.template
  scripts/update-endpoints/typescript.js
  src/EndpointDefaults.ts
  src/RequestParameters.ts
  src/generated/Endpoints.ts
Labels: Type: Feature, Type: Breaking change
